name: Front Web CI/CD Workflow

on:
  push:
    branches:
      # - develop
      - feature/v1.0.0/cicd-front-web
      # - feature/v1.0.0/filter-search-back-filter


jobs:
  health-check-job: 
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      # - name: Cache dependency # caching dependency will make our build faster.
      #   working-directory: ./Backend/bshop
      #   uses: actions/cache@v2 # for more info checkout pip section documentation at https://github.com/actions/cache
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./Frontend/Website/bshop
        run: npm install

      - name: Run the tests
        working-directory: ./Frontend/Website/bshop
        run: npm test

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1

      # - name: Build
      #   run: npm run build

      # - name: Deploy
      #   run: |
      #     git config --global user.name $user_name
      #     git config --global user.email $user_email
      #     git remote set-url origin https://${github_token}@github.com/${repository}
      #     npm run deploy
      #   env:
      #     user_name: 'github-actions[bot]'
      #     user_email: 'github-actions[bot]@users.noreply.github.com'
      #     github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
      #     repository: ${{ github.repository }}


  upload-job: 
    runs-on: ubuntu-latest
    needs: [health-check-job] 
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./Frontend/Website/bshop
          remote: /home/ubuntu/Eunoiateam2/front/web
          host: 37.152.179.124
          username: ubuntu
          password: Eunoia6Team

  dependencies-job: 
    runs-on: ubuntu-latest
    needs: [upload-job]
    steps:
      - name: Install dependencies
        working-directory: /home/ubuntu/Eunoiateam2/front/web/bshop
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: npm install
          host: 37.152.179.124
          username: ubuntu
          password: Eunoia6Team
        # run: npm install
      # - name: migrate ssh
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: | 
      #       source venv/bin/activate
      #       pip3 install -r Eunoiateam2/bshop/requirements.txt
      #       python3 Eunoiateam2/bshop/manage.py migrate
      #     host: 37.152.179.124
      #     username: ubuntu
      #     password: Eunoia6Team
          
  runserver-job: 
    runs-on: ubuntu-latest
    needs: [dependencies-job]
    steps:
      - name: build ssh
      working-directory: /home/ubuntu/Eunoiateam2/front/web/bshop
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: | 
            tmux kill-session -t web
            tmux new -d -s web 'npm run build'
          host: 37.152.179.124
          username: ubuntu
          password: Eunoia6Teams